import type { CaseItem } from "../roulette/types";

export const boozeCase: CaseItem[] = [
	{
		name: "Koskenkorva Vodka 60%",
		rarity: "Rare Special Item",
		weight: 1,
		image: "/viinat/kossu-60.jpg",
		description:
			"https://www.alko.fi/tuotteet/946328/Koskenkorva-Vodka-60-muovipullo/",
	},
	{
		name: "Koskenkorva 38%",
		rarity: "Restricted",
		weight: 1,
		image: "viinat/koskenkorva-38.jpg",
		description: "",
	},
	{
		name: "Koskenkorva 40%",
		rarity: "Covert",
		weight: 1,
		image: "viinat/koskenkorva-40.jpg",
		description: "",
	},
	{
		name: "Tapio",
		rarity: "Classified",
		weight: 1,
		image: "viinat/tapio-39.jpg",
		description: "https://www.alko.fi/tuotteet/104527/",
	},
	{
		name: "Sisuviina",
		rarity: "Mil-spec",
		weight: 1,
		image: "viinat/sisuviina.jpg",
		description: "",
	},
	{
		name: "Suomi Viina",
		rarity: "Mil-spec",
		weight: 1,
		image: "viinat/suomi-viina.jpg",
		description: "",
	},
	{
		name: "Saunalahden Viina",
		rarity: "Consumer",
		weight: 1,
		image: "viinat/saunalahden-viina.jpg",
		description: "",
	},

	{
		name: "Leijona",
		rarity: "Restricted",
		weight: 1,
		image: "viinat/leijona.jpg",
		description: "",
	},
	{
		name: "Tasavalta",
		rarity: "Mil-spec",
		weight: 1,
		image: "viinat/tasavalta.jpg",
		description: "",
	},
	{
		name: "Lithuanian Vodka Classic",
		rarity: "Contraband",
		weight: 1,
		image: "viinat/lithuanian-vodka-classic.jpg",
		description: "",
	},
	{
		name: "Törni Viina",
		rarity: "Restricted",
		weight: 1,
		image: "viinat/torni-viina.jpg",
		description: "",
	},
	{
		name: "762 Viina",
		rarity: "Rare Special Item",
		weight: 0.1,
		image: "viinat/762-viina.jpg",
		description: "",
	},
	{
		name: "Puolustuslaitos",
		rarity: "Rare Special Item",
		weight: 1,
		image: "viinat/puolustuslaitos.jpg",
		description: "",
	},
	{
		name: "Dry Vodka",
		rarity: "Rare Special Item",
		weight: 1,
		image: "viinat/dry-vodka.jpg",
		description: "",
	},
	{
		name: "Saaremaa",
		rarity: "Rare Special Item",
		weight: 1,
		image: "viinat/saaremaa.jpg",
		description: "",
	},
	{
		name: "Finlandia",
		rarity: "Rare Special Item",
		weight: 1,
		image: "viinat/finlandia.jpg",
		description: "",
	},
	{
		name: "Smirnoff",
		rarity: "Rare Special Item",
		weight: 1,
		image: "viinat/smirnoff.jpg",
		description: "",
	},
	{
		name: "Kyrö",
		rarity: "Rare Special Item",
		weight: 1,
		image: "viinat/kyro.jpg",
		description: "",
	},
];
