import type { CSGOItem } from "../roulette/types";

export const mapCase: CSGOItem[] = [
    {
        id: 2,
        name: "Dust II",
        image: "/maps/de_dust2.png",
        rarity: "Consumer",
        weight: 0.5,
    },
    {
        id: 3,
        name: "Mirage",
        image: "/maps/de_mirage.png",
        rarity: "Consumer",
        weight: 0.5,
    },
    {
        id: 4,
        name: "Inferno",
        image: "/maps/de_inferno.png",
        rarity: "Industrial",
        weight: 1,
    },
    {
        id: 9,
        name: "Vertigo",
        image: "/maps/de_vertigo.png",
        rarity: "Industrial",
        weight: 1,
    },
    {
        id: 5,
        name: "Train",
        image: "/maps/de_train.png",
        rarity: "Mil-spec",
        weight: 1,
    },
    {
        id: 10,
        name: "Anubis",
        image: "/maps/de_anubis.png",
        rarity: "Classified",
        weight: 1,
    },
    {
        id: 1,
        name: "Ancient",
        image: "/maps/de_ancient.png",
        rarity: "Industrial",
        weight: 1,
    },
    {
        id: 8,
        name: "Overpass",
        image: "/maps/de_overpass.png",
        rarity: "Mil-spec",
        weight: 1,
    },
    {
        id: 13,
        name: "Nuke",
        image: "/maps/de_nuke.png",
        rarity: "Mil-spec",
        weight: 1,
    },
    {
        id: 11,
        name: "Jura",
        image: "/maps/de_jura.png",
        rarity: "Classified",
        weight: 1,
    },
    {
        id: 12,
        name: "Grail",
        image: "/maps/de_grail.png",
        rarity: "Industrial",
        weight: 1,
    },
    {
        id: 14,
        name: "Agency",
        image: "/maps/cs_agency.png",
        rarity: "Covert",
        weight: 1.1,
    },
    {
        id: 6,
        name: "Office",
        image: "/maps/cs_office.png",
        rarity: "Rare Special Item",
        weight: 1.5,
    },
    {
        id: 7,
        name: "Italy",
        image: "/maps/cs_italy.png",
        rarity: "Classified",
        weight: 1.1,
    },
];